### ISSUE TITLE
Update ObservableList NoSuchMethodError

### ISSUE THREAD

**Issue by joo** [dam0vm3nt/polymer_autonotify#10]
test_elements.html:

``````
<!DOCTYPE html>
<html lang="zh_CN">
<head>
    <meta charset="UTF-8">
</head>
<body>
<dom-module id="table-element">
    <style>
        :host > table {
            text-align: left;
            vertical-align: middle;
            color: black;
            border-collapse: collapse;
            border-spacing: 0;
            padding: 0;
            word-break: keep-all;
            white-space: nowrap;
            outline: none;
        }
        :host > table > tbody > tr > td {
            border: 1px black solid;
            padding: 0.125rem;
        }
    </style>
    <template>
        <template is="dom-repeat" items="{{rows}}" as="row">
            <template is="dom-repeat" items="{{row}}" as="col">
                <div>{{col}}</div>
            </template>
        </template>
        <!--<table>-->
            <!--<tbody>-->
            <!--<template is="dom-repeat" items="{{rows}}" as="row">-->
                <!--<tr>-->
                    <!--<template is="dom-repeat" items="{{row}}" as="col">-->
                        <!--<td>{{col}}a</td>-->
                    <!--</template>-->
                <!--</tr>-->
            <!--</template>-->
            <!--</tbody>-->
        <!--</table>-->
        <button on-click="updateClick">update</button>
    </template>
</dom-module>
</body>
</html>```

test_elements.dart:

`@HtmlImport('test_elements.html')
library test_elements;

import 'dart:html';
import 'package:polymer/polymer.dart';
import 'package:web_components/web_components.dart' show HtmlImport;
import 'package:polymer_autonotify/polymer_autonotify.dart'
    show AutonotifyBehavior;
import "package:observe/observe.dart";

@PolymerRegister('table-element')
class TableElement extends PolymerElement with AutonotifyBehavior, Observable {
  @observable
  @property
  List rows = toObservable([
    [1, 2, 3],
    [4, 5, 6]
  ]);

  TableElement.created() : super.created() {
    rows.add([7, 8, 9]);
  }

  @reflectable
  updateClick(event, detail) {
    rows[0][0] = 11;
  }
}`

click update button show:

`The null object does not have a method 'removeReference'.

NoSuchMethodError: method not found: 'removeReference'
Receiver: null
Arguments: ["0", Instance of 'ListPropertyNotifier']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ListPropertyNotifier.ListPropertyNotifier.<anonymous closure>.<anonymous closure> (package:polymer_autonotify/polymer_autonotify.dart:466:37)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#4      ListIterable.toList (dart:_internal/iterable.dart:219)
#5      ListPropertyNotifier.ListPropertyNotifier.<anonymous closure> (package:polymer_autonotify/polymer_autonotify.dart:511:12)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1075)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#9      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:381)
#10     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:256)
#11     ObservableList.deliverListChanges (package:observe/src/observable_list.dart:265:20)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _ScheduleImmediateHelper._handleMutation (dart:html:48762)
#15     MutationObserver._create.<anonymous closure> (dart:html:27252)`
``````

**Comment by dam0vm3nt** [comment]
You have to use observable objects inside an observable list.

For example try using : 

```
 rows.add(new ObservableList.fromIterable([0,0,0]));
```

**Comment by dam0vm3nt** [comment]
also consider using `iron-data-table` from `custom_elements` if you want a nice table.

**Comment by joo** [comment]
rows.add([0,0,0]), show the expected effect.
rows[0][0] = 11, raise above error.

......
polymer 1.0 more ugly than version 0.5.

**Comment by dam0vm3nt** [comment]
please use an observable list when adding.
